import type { Metadata } from "next";
import "./globals.css";
import {Header, MainLayout} from "@/components/layout";
import {LoadingContextProvider} from "@/context";
import { ReactNode } from 'react';

export const metadata: Metadata = {
  title: "강승택 | 프론트엔드",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={'w-full'}>
        <LoadingContextProvider>
          <Header />
          <MainLayout>
            {children}
          </MainLayout>
        </LoadingContextProvider>
      </body>
    </html>
  );
}
